### ISSUE TITLE
Submission on Proposed FAQ on Blue Pair

### ISSUE THREAD

**Issue by gutzygwin** [aurasphere/blue-pair#18]
I volunteer in contributing to the development of blue pair (simple application for Bluetooth discovery and pairing) by submitting a proposed FAQ on Bluetooth pair application. I noticed it had an about option, but there wasn't an option for FAQ.

Here is a link to the FAQ I created for Blue-Pair, 
https://drive.google.com/file/d/1OMO-T7FfhvwdxRF5w7UWJBU3_oajkayj/view?usp=drivesdk
Edits and criticism are welcomed anytime.
Thank you.

**Comment by aurasphere** [comment]
Hey @gutzygwin thank you very much for your proposal. However this seems out of scope for this project (you can read that on the README.md file) so unfortunately I won't merge it to master. Thanks again!
