### ISSUE TITLE
obfuscate error

### ISSUE THREAD

**Issue by RezaGhanbar** [aurasphere/blue-pair#21]
I obfuscated the app and it crashed with this error.
I put all the view package in proguard keep file with this line : 
-keep public class com.example.phmeter.view

Error:
Binary XML file line #26: Binary XML file line #26: Error inflating class com.example.phmeter.view.RecyclerViewProgressEmptySupport

Caused by java.lang.ClassNotFoundException
Didn't find class "com.example.phmeter.view.RecyclerViewProgressEmptySupport" on path: DexPathList[[zip file "/data/app/com.example.phmeter-MdnZ-1Qx_aIfYqRokPcStQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.phmeter-MdnZ-1Qx_aIfYqRokPcStQ==/lib/arm64, /system/lib64, /product/lib64]]

**Comment by aurasphere** [comment]
Hey @RezaGhanbar , sorry for the late reply but I was on holiday.

This error doesn't seem related to the library (notice the package name and the class which was not found). 

I'm closing this but feel free to reopen in case you feel like I'm wrong. Thanks!
