### ISSUE TITLE
D:\Bluetooth\blue-pair-secret.properties (The system cannot find the file specified)

### ISSUE THREAD

**Issue by Aniket-Softserv** [aurasphere/blue-pair#23]
A problem occurred evaluating project ':app'.
> D:\Bluetooth\blue-pair-secret.properties (The system cannot find the file specified)

**Comment by aurasphere** [comment]
Hey @Aniket-Softserv ! This problem occurs if you're trying to build a production build. In that case, you will have to create a blue-pair-secret.properties on your project with the information required for signing the apk. The file should look like this:

    # Ads configuration
    ad.app.id="ads_app_id_between_quotes"
    ad.unit.id="ads_unit_id_between_quotes"

    # Signing configuration
    release.store.file=<path_to_keystore>
    release.store.password=<keystore_password>
    release.key.alias=<keystore_key_alias>
    release.key.password=<keystore_key_password>

Let me know if you need other info and have a nice day
